    - name: Print message
      ansible.builtin.debug:
        msg: Installing phpLdapAdmin

    - name: Install php apache and phpldapadmin packages
      community.general.apk:
        name: "{{ alpine_phpldapadmin_packages }}"
        state: latest
        update_cache: yes

    - name: Copy the config.php file
      ansible.builtin.copy:
        src: "{{ alpine_phpldapadmin_config.source}}" 
        dest: "{{ alpine_phpldapadmin_config.destination }}"

    - name: Copy the phpldapadmin.conf file
      ansible.builtin.copy:
        src: "{{ alpine_phpldapadmin_phpldapadmin_conf.source }}"
        dest: "{{ alpine_phpldapadmin_phpldapadmin_conf.destination }}"

    - name: Recursively change ownership
      ansible.builtin.file:
        path: "{{ alpine_phpldapadmin_config }}"
        state: directory
        recurse: yes
        owner: "{{ alpine_phpldapadmin_user }}"
        group: "{{ alpine_phpldapadmin_user }}"

    - name: Start service apache2 
      ansible.builtin.service:
        name: apache2
        state: restarted


