    - name: Print message
      ansible.builtin.debug:
        msg: Installing LDAP

    - name: Install LDAP client package
      community.general.apk:
        name: "{{ alpine.ldap.packages }}" 
        state: latest
        update_cache: yes

    - name: Recursively remove directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ alpine.ldap.directories }}"

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ alpine.ldap.directories }}"

    - name: Copy the slapd.conf file
      ansible.builtin.copy:
        src: "{{ alpine.ldap.slapd.source }}"
        dest: "{{ alpine.ldap.slapd.destination }}"

    - name: Copy the edt.org file
      ansible.builtin.copy:
        src: "{{ alpine.ldap.ldif.source }}"
        dest: "{{ alpine.ldap.ldif.destination }}"

    - name: Populate and list
      ansible.builtin.command: slapadd  -l "{{ alpine.ldap.ldif.destination }}"
      ignore_errors: yes

    - name: Recursively change ownership 
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: "{{ alpine.ldap.user }}"
        group: "{{ alpine.ldap.group }}"
      loop: "{{ alpine.ldap.directories }}"

    - name: Start service slapd, if not started
      ansible.builtin.service:
        name: slapd
        state: restarted


