    - name: Print message
      ansible.builtin.debug:
        msg: Installing phpLdapAdmin

    - name: Install php apache and phpldapadmin packages
      community.general.apk:
        name: "{{ alpine.phpldapadmin.packages }}"
        state: latest
        update_cache: yes

    - name: Copy the config.php file
      ansible.builtin.copy:
        src: "{{ alpine.phpldapadmin.config.source}}" 
        dest: "{{ alpine.phpldapadmin.config.destination }}"

    - name: Copy the phpldapadmin.conf file
      ansible.builtin.copy:
        src: "{{ alpine.phpldapadmin.phpldapadmin_conf.source }}"
        dest: "{{ alpine.phpldapadmin.phpldapadmin_conf.destination }}"

    - name: Recursively change ownership
      ansible.builtin.file:
        path: "{{ alpine.phpldapadmin.config }}"
        state: directory
        recurse: yes
        owner: "{{ alpine.phpldapadmin.user }}"
        group: "{{ alpine.phpldapadmin.group }}"

    - name: Start service apache2 
      ansible.builtin.service:
        name: apache2
        state: restarted


