servernet:
  hosts:
    server:
      ansible_host: 192.168.56.10

workersnet:
  hosts:
    worker1:
      ansible_host: 172.30.30.11
    worker2:
      ansible_host: 172.30.30.12
    worker3:
      ansible_host: 172.30.20.13

vagrantlabpublic:
  children:
    servernet:
    workersnet:  
