---
- name: Install LDAP server with edt.org database
  hosts: servernet
  become: true  
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: Installing LDAP

    - name: Print os information
      ansible.builtin.debug:
        msg: "{{ ansible_os_family }}" 
    
    - include_tasks: ./part_playbook_ldap_debian.yaml
      when: ansible_os_family == 'Debian'

- name: Install phpldapadmin
  hosts: servernet
  become: true
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: Installing phpLdapAdmin

    - import_tasks: ./part_playbook_phpldapadmin_debian.yaml
      when: ansible_os_family == "Debian"
