# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #box settings
  config.vm.box = "debian/bullseye64"
  #config.vm.box = "generic/alpine38"

  #provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end
  
  #network settings
  #config.vm.network "private_network", ip: "192.68.33.10"
  config.vm.network "public_network", bridge: "enp1s0"
  config.vm.network "forwarded_port", guest: 389, host: 2389
  config.vm.network "forwarded_port", guest: 80, host: 2080
  config.vm.network "forwarded_port", guest: 22, host: 2022
  config.vm.network "forwarded_port", guest: 139, host: 2139
  config.vm.network "forwarded_port", guest: 445, host: 2445
  
  #folder settings 
  #config.vm.synced_folder "./html/", "/var/www/html", :mount_options => ["dmode=777","fmode=666"]
  
  #provision settings
  #config.vm.provision "shell", path: "install.sh"
  #config.vm.provision "shell", inline: $install_script_debian
 
  config.vm.provision "docker" do |d|
    #d.build_image "/vagrant/app"
    #d.pull_images ["edtasixm06/ldap22:latest", "edtasixm06/ldap22:phpldapadmin", \
    #               "edtasixm06/ssh22:base", "edtasixm06/samba22:homes" ]
    d.pull_images "edtasixm06/ldap22:latest"
    d.pull_images "edtasixm06/ldap22:phpldapadmin"
    d.pull_images "edtasixm06/ssh22:base"
    d.pull_images "edtasixm06/samba22:homes"
    
    #docker run --rm --name ldap.edt.org -h ldap.edt.org --net 2hisx -p 389:389 -d edtasixm06/ldap22:latest
    d.run  "edtasixm06/ldap22:latest",  auto_assign_name: "false", args: " --name ldap.edt.org -h ldap.edt.org -p 389:389"
    #docker run --rm --name phpldapadmin.edt.org -h phpldapadmin.edt.org --net 2hisx -p 80:80 -d edtasixm06/ldap22:phpldapadmin
    d.run "edtasixm06/ldap22:phpldapadmin", auto_assign_name: "false", args: "--name phpldapadmin.edt.org \
           -h phpldapadmin.edt.org -p 80:80"
    #docker run --rm --name ssh.edt.org -h ssh.edt.org --net 2hisx -p 2022:22 -d edtasixm06/ssh22:base
    d.run "edtasixm06/ssh22:base", auto_assign_name: "false", args: "--name ssh.edt.org -h ssh.edt.org -p 2022:22"
    #docker run --rm --name samba.edt.org -h samba.edt.org --net 2hisx -p 139:139 -p 445:445 --privileged -d edtasixm06/samba22:homes
    d.run "edtasixm06/samba22:homes",  auto_assign_name: "false", args:  "--name samba.edt.org -h samba.edt.org \
         -p 139:139 -p 445:445 --privileged"
  end

end


$install_script_debian = <<SCRIPT
#!/bin/bash
sudo apk add git nmap tree 
sudo mkdir -p /usr/share/edtasix
cd /usr/share/edtasix
sudo git clone https://gitlab.com/edtasixm06/M06-ASO
cd -
docker pull edtasixm06/ldap22:latest
docker pull edtasixm06/ldap22:phpldapadmin
docker pull edtasixm06/ssh22:base
docker pull edtasixm06/samba22:homes
docker images
docker network create 2hisx || echo "Network exists: 2hisx"
docker run --rm --name ldap.edt.org -h ldap.edt.org --net 2hisx -p 389:389 -d edtasixm06/ldap22:latest
docker run --rm --name phpldapadmin.edt.org -h phpldapadmin.edt.org --net 2hisx -p 80:80 -d edtasixm06/ldap22:phpldapadmin
docker run --rm --name ssh.edt.org -h ssh.edt.org --net 2hisx -p 2022:22 -d edtasixm06/ssh22:base
docker run --rm --name samba.edt.org -h samba.edt.org --net 2hisx -p 139:139 -p 445:445 --privileged -d edtasixm06/samba22:homes
SCRIPT

# Docker network
# https://developer.hashicorp.com/vagrant/docs/providers/docker/networking
#  docker.vm.network :private_network, type: "dhcp", name: "my-custom-network"
#  docker.vm.network :private_network, type: "dhcp", docker_network__internal: true
#    docker.vm.network :private_network,
#        ip: "172.20.128.2", netmask: "16"
#    docker.vm.network :private_network, type: "dhcp", subnet: "2a02:6b8:b010:9020:1::/80"

# https://github.com/hashicorp/vagrant/issues/9873
#config.trigger.before :up do |trigger|
#  trigger.name = 'Create network vagrant'
#  trigger.run = { inline: 'docker network create vagrant' }
#end
#
#config.trigger.after :destroy do |trigger|
#  trigger.name = 'Remove network vagrant'
#  trigger.run = { inline: 'docker network rm vagrant' }
#end
