- name: My first play
  hosts: all
  become: yes
  #become_user: <name-user>   
  tasks:
#    - name: Ensure docker is at the latest version
#      ansible.builtin.apt:
#        name: docker
#        state: latest
#    - name: Ensure that docker is started
#      ansible.builtin.service:
#        name: docker
#        state: started
    #---------------------------------------------
    - name: apt-get update
      ansible.builtin.apt:
        pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release 
        - tree 
    - name: Creates directory
      file:
        path: /etc/apt/keyrings        
        state: directory
        mode: '0755'
    - name: Download GPG key
      shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg'
    - name: Append docker repo
      shell: 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null'
    - name: install docker
      ansible.builtin.apt:
        pkg:
        - tree
        - docker-ce 
        - docker-ce-cli 
        - containerd.io 
        - docker-buildx-plugin 
        - docker-compose-plugin

# -------------------------------------------------------------------
# ansible-playbook -u ansible --private-key ./ansible_key \
#                   -i inventory.yaml playbook.yaml 
# --------------------------------------------------------------------
# Install Docker febian 11
# sudo apt-get remove docker docker-engine docker.io containerd runc
# sudo apt-get update
# sudo apt-get install ca-certificates curl gnupg lsb-release
# sudo mkdir -m 0755 -p /etc/apt/keyrings
# curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
# echo \
#  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
#  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
# sudo apt-get update  
# sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

