# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #box settings
  config.vm.box = "debian/bullseye64"
  #config.vm.box = "generic/alpine38"

  #provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end
  
  #network settings
  #config.vm.network "private_network", ip: "192.68.33.10"
  config.vm.network "public_network", bridge: "enp1s0"
  #config.vm.network "forwarded_port", guest: 389, host: 2389
  
  #folder settings 
  #config.vm.synced_folder "./html/", "/var/www/html", :mount_options => ["dmode=777","fmode=666"]
  
  #provision settings
  #config.vm.provision "shell", path: "install.sh"
  config.vm.provision "shell", inline: $install_aula_script_debian
end


$install_aula_script_debian = <<SCRIPT
sudo apt-get update
sudo apt-get -y install vim vim-gtk3 mc geany aptitude tree git openssh-server
sudo apt-get -y purge gnome-games 
sudo apt-get -y autoremove 
# pendent: eliminar pregunta interactiva
sudo apt-get -y install krb5-user krb5-multidev libpam-mount sssd nfs-common autofs ufw curl 
git clone https://gitlab.com/manelmellado/ubnt-at-inf.git
#cd ubnt-at-inf/Debian\ 11/arxius/etc/
sudo cp ubnt-at-inf/Debian\ 11/arxius/etc/sssd/sssd.conf /etc/sssd/
sudo cp ubnt-at-inf/Debian\ 11/arxius/etc/sudoers.d/inf /etc/sudoers.d/
sudo chmod 600 /etc/sssd/sssd.conf
# pendent: eliminar pregunta interactiva
sudo pam-auth-update
sudo systemctl disable sssd-nss.socket
sudo systemctl disable sssd-autofs.socket
sudo systemctl restart sssd
sudo systemctl restart rpc-gssd
# Editar fstab
sudo apt-get -y install gpm pwgen
sudo sed -i '/^[^#]/  s/main$/main contrib non-free/' /etc/apt/sources.list
sudo apt-get update
sudo apt-get -y install chromium vlc gimp git tig meld linux-headers-`uname -r` gnome-shell-extension-desktop-icons terminator firmware-realtek firmware-misc-nonfree hunspell-ca hunspell-es
AULA=profeF2G
SERVER=10.200.247.246
line="$SERVER $AULA.informatica.escoladeltreball.org server"
sudo bash -c "echo $line >> /etc/hosts"
sudo apt-get -y install --install-recommends epoptes-client -y
sudo epoptes-client -c  $AULA.informatica.escoladeltreball.org
sudo apt-mark hold linux-image-$(uname -r) # per apt-get
sudo aptitude hold linux-image-$(uname -r) # per aptitude
sudo apt-mark hold linux-headers-$(uname -r) # per apt-get
sudo aptitude hold linux-headers-$(uname -r) # per aptitude
#sed -i 's/\#WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/daemon.conf
SCRIPT

