    - name: Install packages and dependencies
      ansible.builtin.apt:
        name: "{{ debian.phpldapadmin.packages }}"
        update_cache: yes

    - name: Install a .deb package from the internet
      ansible.builtin.apt:
        deb: "{{ debian.phpldapadmin.debpkg }}"

    - name: Copy the config.php file
      ansible.builtin.copy:
        src: "{{ debian.phpldapadmin.config.source }}"
        dest: "{{ debian.phpldapadmin.config.destination }}"

    - name: Copy the phpldapadmin.conf file
      ansible.builtin.copy:
        src: "{{ debian.phpldapadmin.phpldapadmin_conf.source }}"
        dest: "{{ debian.phpldapadmin.phpldapadmin_conf.destination }}"
          
    - name: Start service apache2, if not started
      ansible.builtin.service:
        name: apache2
        state: restarted


