# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #box settings
  #config.vm.box = "debian/bullseye64"
  config.vm.box = "generic/alpine38"

  #provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096
    vb.cpus = 2
  end
  
  #network settings
  #config.vm.network "private_network", ip: "192.68.33.10"
  config.vm.network "public_network", bridge: "enp1s0"
  config.vm.network "forwarded_port", guest: 389, host: 2389
  config.vm.network "forwarded_port", guest: 80, host: 2080
  
  #folder settings 
  #config.vm.synced_folder "./html/", "/var/www/html", :mount_options => ["dmode=777","fmode=666"]
  config.vm.synced_folder ".", "/vagrant" 
 
  #provision settings
  #config.vm.provision "shell", path: "install.sh"
  config.vm.provision "shell", inline: $install_ldap_script_alpine
  config.vm.provision "shell", inline: $install_phpldapadmin_script_alpine
end

$install_ldap_script_alpine = <<SCRIPT
sudo apk add openldap openldap-back-mdb openldap-back-monitor
sudo rm -rf /etc/openldap/slapd.d/*
sudo rm -rf /var/lib/openldap/*
sudo cp /etc/openldap/DB_CONFIG.example /var/lib/openldap/.
#sudo slaptest -Q -f /vagrant/ldap/slapd_alpine.conf -F /etc/openldap/slapd.d &> /dev/null
#sudo slapadd -F /etc/ldap/slapd.d -l /vagrant/ldap/edt.org.ldif
sudo cp /vagrant/ldap/slapd_alpine.conf /etc/openldap/slapd.conf
sudo slapadd -l /vagrant/ldap/edt.org.ldif
#sudo chown -R ldap.ldap /etc/openldap/slapd.d
sudo chown -R ldap.ldap /var/lib/openldap
sudo cp /vagrant/ldap/ldap.conf /etc/openldap/ldap.conf
sudo service slapd start
sudo service slapd restart
SCRIPT

# En el host amfitrió per verificar que funciona ldap:
# ldapsearch -x -LLL -H ldap://localhost:2389 -b 'dc=edt,dc=org'
# ldapsearch -x -LLL -h <ip-vm> -b 'dc0edt,dc=org'

$install_phpldapadmin_script_alpine = <<SCRIPT
sudo apk update
# nota: cal insta·lar php5-aache2 perquè phpldapadmin l'utilitza 
# i no el php7-apach2 (no: php$phpverx-apache2)
sudo apk add apache2  php5-apache2 phpldapadmin
sudo cp /vagrant/phpldapadmin/phpldapadmin_alpine.conf /etc/apache2/conf.d/phpldapadmin.conf
sudo cp /vagrant/phpldapadmin/config.php  /etc/phpldapadmin/config.php
sudo chgrp apache /etc/phpldapadmin/config.php
# Repassar el mecanisme d'assignació del nom ldap.edt.org al host local
#sudo bash -c "echo 192.168.1.41 ldap.edt.org >> /etc/hosts"
sudo sed -i 's/alpine38.localdomain/alpine38.localdomain ldap.edt.org/' /etc/hosts
sudo service apache2 start
SCRIPT

# Verificar php: echo "<?php phpinfo(); ?>" /var/www/localhost/htdocs/index.php
# Des d'un altre host connectar al port 2080 (propagat) o al 80 de la vm 
# # localhost:280/phpldapadmin
# # <ip-vm-phpldapadmin>:80/phpldapadmin




