---
- name: Install LDAP server with edt.org database
  hosts: default
  become: true  
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: Installing LDAP

    - name: Install LDAP client package
      ansible.builtin.apt:
        name: ldap-utils
        state: present
        update_cache: yes

    - name: Install LDAP server package
      ansible.builtin.apt:
        name: slapd
        state: present  

    - name: Install package utilities
      ansible.builtin.apt:
        pkg:
        - tree
        - nmap
        - vim

    - name: Recursively remove directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: 
        - /etc/ldap/slapd.d
        - /var/lib/ldap

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/ldap/slapd.d
        - /var/lib/ldap

    - name: Copy the slapd.conf file
      ansible.builtin.copy:
        src: ./slapd.conf
        dest: /etc/ldap/slapd.conf

    - name: Copy the edt.org file
      ansible.builtin.copy:
        src: ./edt-org.ldif
        dest: /etc/ldap/edt-org.ldif
          
    - name: Create dynamic configuration
      ansible.builtin.command: slaptest -f /etc/ldap/slapd.conf -F /etc/ldap/slapd.d
      ignore_errors: yes

    - name: Populate ans list
      ansible.builtin.command: "{{ item }}"
      ignore_errors: yes
      loop:
        - slaptest -f /etc/ldap/slapd.conf -F /etc/ldap/slapd.d -u
        - slapadd  -F /etc/ldap/slapd.d -l /etc/ldap/edt-org.ldif
        - slapcat 

    - name: Recursively change ownership 
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: yes
        owner: openldap
        group: openldap
      loop: [ /etc/ldap/slapd.d, /var/lib/ldap ]
      #loop:
        #- /etc/ldap/slapd.d
        #- /var/lib/ldap

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: slapd
        state: restarted

# Configuració BD edt.org ----------------------------------
# rm -rf /etc/ldap/slapd.d/*
# rm -rf /var/lib/ldap/*
# slaptest -f /opt/docker/slapd.conf -F /etc/ldap/slapd.d
# slapadd  -F /etc/ldap/slapd.d -l /opt/docker/edt-org.ldif
# slapcat    
# chown -R openldap.openldap /etc/ldap/slapd.d /var/lib/ldap
# /usr/sbin/slapd -d0 
# -----------------------------------------------------------
#---
- name: Install phpldapadmin 
  hosts: servernet
  become: true  
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: Installing phpLdapAdmin

    - name: Install packages and dependencies
      ansible.builtin.apt:
        pkg:
        - php-xml 
        - apache2 
        - tree
        - nmap
        - vim   
        update_cache: yes

    - name: Install a .deb package from the internet
      ansible.builtin.apt:
        deb: http://ftp.de.debian.org/debian/pool/main/p/phpldapadmin/phpldapadmin_1.2.6.3-0.2_all.deb

    - name: Copy the config.php file
      ansible.builtin.copy:
        src: ./config.php
        dest: /etc/phpldapadmin/config.php

    - name: Copy the phpldapadmin.conf file
      ansible.builtin.copy:
        src: ./phpldapadmin.conf
        dest: /etc/apache2/conf-enabled/phpldapadmin.conf
          
    - name: Start service apache2 
      ansible.builtin.service:
        name: apache2
        state: restarted

#$install_phpldapadmin_script_debian = <<SCRIPT
#sudo apt-get update
#sudo apt-get -y install php-xml apache2
#wget http://ftp.de.debian.org/debian/pool/main/p/phpldapadmin/phpldapadmin_1.2.6.3-0.2_all.deb
##sudo apt-get -y install http://ftp.de.debian.org/debian/pool/main/p/phpldapadmin/phpldapadmin_1.2.6.3-0.2_all.deb
#sudo apt-get -y install ./phpldapadmin_1.2.6.3-0.2_all.deb
#sudo cp /vagrant/phpldapadmin/phpldapadmin.conf /etc/apache2/conf-enabled/phpldapadmin.conf
#sudo cp /vagrant/phpldapadmin/config.php  /etc/phpldapadmin/config.php
#sudo bash -c "echo 192.168.1.41 ldap.edt.org >> /etc/hosts"
#sudo bash -c "echo $ldap_ip ldap.edt.org" >> /tmp/hosts
#sudo systemctl start apache2
#SCRIPT

